NumPy (Numerical Python):- It's a Python Library used to perform various mathematical operations on array

In [4]:
import numpy as np

In [4]:
#creating 1-D Array
a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

Converting List to Array

In [5]:
l = [1,2,3,4,5]
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [6]:
a = np.array(l)
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

Converting Other Data Structures to Array

In [12]:
t = (1,2,4,5,3) #tuple
a = np.array(t)
type(a)
print(a)

[1 2 4 5 3]


In [14]:
len(a)

5

In [5]:
s = {1,2,3,4,'string'}  #set(it won't change all datatypes to string since all are unique elements)
a = np.array(s)
print(a)

{1, 2, 3, 4, 'string'}


In [11]:
len(a)

TypeError: len() of unsized object

In [8]:
type(a)

numpy.ndarray

In [23]:
s = {1,2,3,2,4,2,1,3,2,5}
a = np.array(s)
print(a)   #since it contains all unique elements it won't change the {} to []

{1, 2, 3, 4, 5}


In [24]:
len(a)

TypeError: len() of unsized object

In [14]:
l1 = [1,2,3,4,5,'cat']
a = np.array(l1)
print(a)
#it'll convert every element to string

['1' '2' '3' '4' '5' 'cat']


In [19]:
#dictionary just change it's datatype 
dict = {1:'a' , 2:'b' , 3:'c'}
a = np.array(dict)
print(a)  #printing the same dictionary

{1: 'a', 2: 'b', 3: 'c'}


In [21]:
len(a)

TypeError: len() of unsized object

Sets & Dictionaries can't ne coverted into Arrays and hence can't use Array Methods

In [18]:
type(a) #only change in datatype

numpy.ndarray

Creating 2-D Array

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
type(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [23]:
a = np.array([(1,2,3),[4,5,6],[7,8,9]])
'''The outmost bracket should be a [] but the nested lists can be one tuple & rest lists,all tuples or 
all lists but can't take sets or will throw error in some cases of length mismatch'''
'''For set,it won't convert it into a 2d matrix,it'll consider that as  a 1-d matrix'''
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
d = np.array([{1,2,3},{4,5,6},{1,2,3}])
d
d[1][0] #error bcuz it's considered as a 1D array and not 2D array

TypeError: 'set' object is not subscriptable

In [31]:
d[0] #won't show any error cuz it's linear

{1, 2, 3}

In [35]:
d = np.array([{1,2,3},{4,5,6},(1,2,3)]) #must contain all sets or will throw error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [24]:
c = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7],[2,4,6,8]])
print(c)

[[1 2 3 4]
 [5 6 7 8]
 [1 3 5 7]
 [2 4 6 8]]


ARRAY Attributes

In [26]:
c.shape  '''to check the size of 2d array'''

(4, 4)

In [27]:
c.size  '''to check the number of elements'''

16

In [28]:
c.ndim  '''to know the dimensions of array'''

2

arange(array range) :- It returns a 1d array of given range

In [18]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

One's Array

In [33]:
np.ones(4)

array([1., 1., 1., 1.])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Full array:- Custom array of same elements and custom size                                               
full(length,element)

In [36]:
np.full(4,6)

array([6, 6, 6, 6])

In [51]:
np.full((4,4),10) #2nd matrix can be strings,space or any datatype

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [39]:
np.eye(4) '''To create an identity matrix'''

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

linspace :- Equally distributed numbers

In [40]:
np.linspace(1,100,10) '''10 letters between 1 and 12 and so on'''

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [41]:
np.linspace(1,100,200)

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

Random Numbers

In [43]:
np.random.rand()

0.3429929559262843

In [46]:
np.random.rand(5)   #5 elements of random numbers

array([0.35378011, 0.60806168, 0.32731039, 0.74038714, 0.04370151])

In [49]:
 np.random.rand(3,4) #for 2d matrix

array([[0.05139526, 0.85924297, 0.83424852, 0.60663143],
       [0.69553155, 0.97623125, 0.85816188, 0.95072231],
       [0.78829893, 0.86055399, 0.76786493, 0.06739233]])

In [50]:
np.random.rand(3,4) * 100 #random numbers under 100

array([[87.63040301, 26.95291497, 48.20355291, 83.27100072],
       [75.43204848, 65.4418155 , 48.74135787, 10.77865763],
       [10.72202154, 41.06694896,  8.42473414, 46.57285256]])

In [53]:
np.random.randint(1,10)

4

In [38]:
np.random.randint(1,10,4)

array([4, 6, 9, 7])

In [54]:
np.random.randint(1,10,(3,4))

array([[2, 5, 1, 6],
       [2, 2, 8, 5],
       [9, 9, 9, 1]])

In [59]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l1+l2

[1, 2, 3, 4, 5, 6, 7, 8]

In [70]:
a = np.array(l1)
b = np.array(l2)
a+b

array([ 6,  8, 10, 12])

Mathematical Array Functions

In [71]:
np.add(a,b)
np.subtract(a,b)

array([-4, -4, -4, -4])

In [73]:
np.multiply(a,b)

array([ 5, 12, 21, 32])

In [44]:
#multiply is not applicable for 2D arrays,it'll multiply matrix element wise so,we need matrix of same size
a = [[1,2,3],[1,2,3]]
b = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(a)
y = np.array(b)
np.multiply(x,y)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [74]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [75]:
np.mod(a,b)

array([1, 2, 3, 4])

In [76]:
np.divmod(a,b) #returns both division and mod

(array([0, 0, 0, 0]), array([1, 2, 3, 4]))

In [77]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [78]:
np.power(a,2)

array([ 1,  4,  9, 16], dtype=int32)

In [79]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [81]:
np.sin(b)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [82]:
top = np.log(a)   #to find log of custom base
base = np.log(3)
np.divide(top,base)

array([0.        , 0.63092975, 1.        , 1.26185951])

In [83]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [84]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [85]:
np.tan(b)

array([-3.38051501, -0.29100619,  0.87144798, -6.79971146])

In [88]:
np.divide(1,np.tan(b))

array([-0.29581292, -3.436353  ,  1.14751542, -0.14706506])

Statistical operators

In [94]:
a.max()

4

In [91]:
a.min()

1

In [92]:
np.median(a)

2.5

In [93]:
 np.mean(a)

2.5

In [95]:
a.std()

1.118033988749895

In [96]:
a.var()

1.25

In [97]:
b.cumsum()  #cumulative sum

array([ 5, 11, 18, 26])

In [100]:
#repeat :- repeat every elements 
a = np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [101]:
np.repeat(a[2],4)

array([3, 3, 3, 3])

In [102]:
#tile :- repeats the whole sequence n times
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [103]:
np.tile(a[2],4)

array([3, 3, 3, 3])

WHERE :- Returns all the positions containing the required element

In [106]:
b = np.array([1,2,3,4,1,3,2,3,1,3,5,6,7,7,9])
np.where(b == 1)

(array([0, 4, 8], dtype=int64),)

In [107]:
np.where(b%2 == 0)

(array([ 1,  3,  6, 11], dtype=int64),)

Slicing / Indexing

In [109]:
arr = np.array([1,3,56,78,90,45,67])
print(arr)

[ 1  3 56 78 90 45 67]


In [110]:
a[-1]

4

In [111]:
a[-1:-4:-1]

array([4, 3, 2])

Slicing / Indexing In 2D Matrix

In [47]:
b = np.random.randint(1,50,(4,4))
print(b)

[[ 7 30 25  8]
 [31 45  1 45]
 [35  6 38 46]
 [49 29 30 33]]


In [49]:
b[3,1]
b[3][1]

29

In [120]:
b[3] #returns the 3rd element of 2d matrix or the row

array([23,  6, 41,  6])

Row Slicing & Column Slicing

In [123]:
b[0:2,0:3]

array([[17, 41, 18],
       [38,  7, 10]])

In [124]:
b[:,:]

array([[17, 41, 18, 19],
       [38,  7, 10, 43],
       [15, 13,  2, 37],
       [23,  6, 41,  6]])

In [130]:
b[:,::2]    #all rows,even column

array([[17, 18],
       [38, 10],
       [15,  2],
       [23, 41]])

In [128]:
b[::2,::2]    #odd rows,odd column

array([[17, 18],
       [15,  2]])

In [131]:
a = np.random.randint(1,20,(2,2))
print(a)

[[ 2  2]
 [13 18]]


In [135]:
b =np.random.randint(1,20,(2,4))
print(b)

[[ 6  4  4 12]
 [ 5 15 15  2]]


In [134]:
c =np.random.randint(1,20,(4,4))
print(c)

[[ 1  1  1  7]
 [ 3 16  6 10]
 [12 18  6 10]
 [ 3  4  7  1]]


AXIS Attribute To Concatenate

In [136]:
d = np.concatenate((a,b),axis = 1) #side by side adhesion
d

array([[ 2,  2,  6,  4,  4, 12],
       [13, 18,  5, 15, 15,  2]])

In [140]:
e = np.concatenate((b,c),axis = 0) #top on top adhesion
e

array([[ 6,  4,  4, 12],
       [ 5, 15, 15,  2],
       [ 1,  1,  1,  7],
       [ 3, 16,  6, 10],
       [12, 18,  6, 10],
       [ 3,  4,  7,  1]])

In [142]:
d.shape

(2, 6)

STACKING : V-STACK & H-STACK

In [144]:
e = np.hstack((a,b))
print(e)

[[ 2  2  6  4  4 12]
 [13 18  5 15 15  2]]


In [146]:
v = np.vstack((b,c))
print(v)

[[ 6  4  4 12]
 [ 5 15 15  2]
 [ 1  1  1  7]
 [ 3 16  6 10]
 [12 18  6 10]
 [ 3  4  7  1]]


Both the above methods have the same functionality

Other Random Functions

In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])   #transpose
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [2]:
np.diagonal(a)

array([1, 5, 9])

In [14]:
np.flip(a)   #Reverse the order of elements in an array along the given axis.
#if no parameter is given it'll flip and rotate

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [15]:
np.flip(a,0) #it will flip vertically

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [16]:
np.flip(a,1)   #it will flip horizontally

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [8]:
d = np.fliplr(a) #Reverse the order of elements along axis 1 (left/right).
d

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [7]:
np.diagonal(d)

array([3, 5, 7])

Ways Of Creating Direct Matrix

In [9]:
np.matrix('1 2 3; 4 5 6')

matrix([[1, 2, 3],
        [4, 5, 6]])

In [10]:
np.matrix([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])